"""Structured query layer.

The central design decision of this prototype lives here.

A natural-language question is never answered directly by a language model.
It is first compiled into a QuerySpec -- a small, typed, inspectable
intermediate representation -- which a deterministic executor runs against the
pre-built index. The executor returns computed facts and the exact evidence
rows behind them.

    "which BU has the most critical exposure?"
        -> QuerySpec(intent=GROUP_EXPOSURE, group_by='department', ...)
        -> executor  -> {rows: [...], facts: {...}, citations: [...]}
        -> narration (template, or LLM constrained to those facts)

Consequences that matter for a security tool:
  * Every number in an answer was computed by Python, not generated by a model.
  * The spec can be printed, so an analyst can see how their question was
    interpreted and challenge the interpretation.
  * The same spec always yields the same answer.
  * If the LLM is unavailable, the deterministic router still answers.
"""

import re
from dataclasses import dataclass, field, asdict
from datetime import date, datetime
from typing import Any, Dict, List, Optional

# ---------------------------------------------------------------------------
# Intents
# ---------------------------------------------------------------------------

TOP_RISKS = "top_risks"            # ranked finding list
TOP_ASSET = "top_asset"            # single riskiest asset + why
PATCH_PRIORITY = "patch_priority"  # which package to fix first (fleet-wide)
GROUP_EXPOSURE = "group_exposure"  # roll-up by department / type / criticality
OVERDUE_KEV = "overdue_kev"        # past CISA due date
POSTURE_SUMMARY = "posture_summary"
CVE_LIST = "cve_list"              # flat CVE listing
WHAT_IF_PATCH = "what_if_patch"    # counterfactual: patch product X
STALE_SCANS = "stale_scans"
COVERAGE = "coverage"              # what the system did NOT assess
COUNT = "count"

ALL_INTENTS = [
    TOP_RISKS, TOP_ASSET, PATCH_PRIORITY, GROUP_EXPOSURE, OVERDUE_KEV,
    POSTURE_SUMMARY, CVE_LIST, WHAT_IF_PATCH, STALE_SCANS, COVERAGE, COUNT,
]


@dataclass
class QuerySpec:
    intent: str
    department: Optional[str] = None
    asset_type: Optional[str] = None
    criticality: Optional[str] = None
    product: Optional[str] = None
    min_cvss: Optional[float] = None
    severity: Optional[str] = None
    kev_only: bool = False
    overdue_only: bool = False
    stale_days: Optional[int] = None
    include_uncertain: bool = True
    group_by: Optional[str] = None
    sort_by: str = "risk"          # risk | cvss | due_date
    limit: int = 10
    # provenance of the spec itself
    planner: str = "rules"         # rules | llm
    interpretation: str = ""

    def to_dict(self) -> dict:
        return asdict(self)


# ---------------------------------------------------------------------------
# Deterministic router
# ---------------------------------------------------------------------------

DEPARTMENTS = ["Finance", "Engineering", "Operations", "HR", "IT", "Executive"]
ASSET_TYPES = {"server": "server", "servers": "server",
               "workstation": "workstation", "workstations": "workstation",
               "laptop": "workstation", "endpoint": "workstation",
               "network device": "network_device", "network devices": "network_device",
               "router": "network_device", "switch": "network_device",
               "firewall": "network_device"}

PRODUCT_HINTS = [
    "Apache HTTP Server", "Apache Tomcat", "log4j-core", "OpenSSL", "OpenSSH",
    "PostgreSQL", "Microsoft SQL Server", "Python", "Node.js", "Ruby", "OpenJDK",
    "Jenkins", "GitLab CE", "Git", "Docker", "Grafana", "Prometheus",
    "Sonatype Nexus Repository Manager", "Microsoft Exchange Server",
    "Microsoft Office", "Internet Explorer", "Visual Studio Code",
    "Microsoft .NET Framework", "Google Chrome", "Mozilla Firefox",
    "Adobe Acrobat Reader", "7-Zip", "PuTTY", "WinSCP", "Zoom", "Nmap",
    "Cisco IOS XE", "Cisco IOS", "Fortinet FortiOS", "F5 BIG-IP",
    "Veeam Backup & Replication", "NGINX",
]


def route(question: str) -> QuerySpec:
    """Compile a question into a QuerySpec using keyword rules.

    This is the fallback planner and the reference implementation of what the
    LLM planner is allowed to produce. It handles the documented benchmark
    questions; it is not a general NL understander, and it says so by
    defaulting to TOP_RISKS rather than guessing wildly.
    """
    q = question.lower().strip()
    spec = QuerySpec(intent=TOP_RISKS)

    # --- filters ---------------------------------------------------------
    for d in DEPARTMENTS:
        if re.search(rf"\b{d.lower()}\b", q):
            spec.department = d
            break
    for phrase, canon in sorted(ASSET_TYPES.items(), key=lambda kv: -len(kv[0])):
        if re.search(rf"\b{re.escape(phrase)}\b", q):
            spec.asset_type = canon
            break
    for p in PRODUCT_HINTS:
        if p.lower() in q:
            spec.product = p
            break

    if re.search(r"\bcritical\b", q):
        spec.severity = "CRITICAL"
    elif re.search(r"\bhigh[- ]severity\b|\bhigh severity\b", q):
        spec.severity = "HIGH"

    if re.search(r"actively exploited|exploited in the wild|kev\b|known exploited", q):
        spec.kev_only = True

    m = re.search(r"(?:cvss|score)\D{0,12}(\d+(?:\.\d+)?)", q)
    if m:
        spec.min_cvss = float(m.group(1))

    m = re.search(r"(\d+)\s*days?", q)
    if m:
        spec.stale_days = int(m.group(1))

    # --- intent ----------------------------------------------------------
    if re.search(r"what (would|does|will).*(patch|patching)|if we patch|reduce our cve count", q):
        spec.intent = WHAT_IF_PATCH
    elif re.search(r"(which|what) (software|package|product).*(patch|first)|patch first|"
                   r"most exposure across", q):
        spec.intent = PATCH_PRIORITY
        spec.group_by = "product"
    elif re.search(r"not been scanned|haven'?t been scanned|last scan|stale scan|"
                   r"not scanned", q):
        spec.intent = STALE_SCANS
        spec.stale_days = spec.stale_days or 30
    elif re.search(r"due date.*(passed|overdue)|overdue|past due|already passed", q):
        spec.intent = OVERDUE_KEV
        spec.kev_only = True
        spec.overdue_only = True
    elif re.search(r"summar(y|ise|ize).*(ciso|posture)|overall.*posture|"
                   r"posture.*(ciso|3 sentences)", q):
        spec.intent = POSTURE_SUMMARY
    elif re.search(r"(business unit|department|bu)\b.*(most|highest|worst)|"
                   r"which (business unit|department)", q):
        spec.intent = GROUP_EXPOSURE
        spec.group_by = "department"
    elif re.search(r"highest[- ]risk|riskiest|most at risk|worst.*(server|asset|host)", q):
        spec.intent = TOP_ASSET
    elif re.search(r"^how many|\bhow many\b", q):
        spec.intent = COUNT
    elif re.search(r"list all cve|all cves|list.*cves|sorted by cvss", q):
        spec.intent = CVE_LIST
        if "cvss" in q:
            spec.sort_by = "cvss"
    elif re.search(r"what (did|didn'?t) you (check|assess)|coverage|not assessed|"
                   r"blind spot", q):
        spec.intent = COVERAGE
    elif re.search(r"which .*(assets?|servers?|hosts?).*(have|with|running)", q):
        spec.intent = TOP_RISKS

    if spec.intent == TOP_RISKS and spec.severity == "CRITICAL":
        spec.limit = 25

    spec.interpretation = _describe(spec)
    return spec


def _describe(s: QuerySpec) -> str:
    bits = [f"intent={s.intent}"]
    for k in ("department", "asset_type", "product", "severity", "min_cvss",
              "stale_days", "group_by"):
        v = getattr(s, k)
        if v:
            bits.append(f"{k}={v}")
    if s.kev_only:
        bits.append("kev_only=True")
    if s.overdue_only:
        bits.append("overdue_only=True")
    return ", ".join(bits)


# ---------------------------------------------------------------------------
# Executor
# ---------------------------------------------------------------------------

SEVERITY_MIN = {"CRITICAL": 9.0, "HIGH": 7.0, "MEDIUM": 4.0, "LOW": 0.1}


def _as_date(s: Optional[str]) -> Optional[date]:
    if not s:
        return None
    try:
        return datetime.strptime(s[:10], "%Y-%m-%d").date()
    except ValueError:
        return None


class Engine:
    """Executes QuerySpecs against a built index."""

    def __init__(self, index: dict):
        self.index = index
        self.findings: List[dict] = index["findings"]
        self.assets: List[dict] = index["assets"]
        self.gaps: List[dict] = index.get("coverage_gaps", [])
        self.as_of = _as_date(index.get("as_of")) or date.today()
        self.actions: List[dict] = self._build_actions()

    # -- remediation actions ---------------------------------------------
    def _build_actions(self) -> List[dict]:
        """Collapse findings into (asset, product) remediation actions.

        This is the unit a patching team works in: one package on one host is
        one ticket, one change window, one reboot — regardless of whether the
        upgrade closes three CVEs or three thousand.
        """
        from . import score as S

        buckets: Dict[tuple, List[dict]] = {}
        for f in self.findings:
            buckets.setdefault((f["asset_id"], f["product"]), []).append(f)

        actions = []
        for (asset_id, product), fs in buckets.items():
            scored = [f for f in fs if f["cvss_score"] is not None]
            worst = max(scored, key=lambda f: f["cvss_score"]) if scored else fs[0]
            kev = [f for f in fs if f["in_kev"]]
            dues = sorted(f["kev_due_date"] for f in kev if f.get("kev_due_date"))

            a = {
                "asset_id": asset_id,
                "hostname": fs[0]["hostname"],
                "department": fs[0]["department"],
                "criticality": fs[0]["criticality"],
                "asset_type": fs[0]["asset_type"],
                "last_scan_date": fs[0]["last_scan_date"],
                "product": product,
                "installed_version": fs[0]["installed_version"],
                "cve_count": len({f["cve_id"] for f in fs}),
                "kev_cve_count": len({f["cve_id"] for f in kev}),
                "kev_cves": sorted({f["cve_id"] for f in kev}),
                "max_cvss": worst["cvss_score"],
                "max_cvss_cve": worst["cve_id"],
                "earliest_due": dues[0] if dues else None,
                "overdue": bool(dues and (_as_date(dues[0]) or date.max) < self.as_of),
                "ransomware": any((f.get("kev_ransomware") or "").lower() == "known"
                                  for f in kev),
                "confidence": ("CONFIRMED"
                               if all(f["confidence"] == "CONFIRMED" for f in fs)
                               else "MIXED"),
                # top evidence rows, so an analyst can drill in without loading
                # thousands of CVEs
                "top_findings": sorted(
                    fs, key=lambda f: (-(f["cvss_score"] or 0), not f["in_kev"]))[:5],
            }
            actions.append(S.score_action(a, self.as_of))

        return sorted(actions, key=lambda a: (-a["risk_score"], a["asset_id"]))

    def _filter_actions(self, s: QuerySpec) -> List[dict]:
        out = []
        for a in self.actions:
            if s.department and a["department"] != s.department:
                continue
            if s.asset_type and a["asset_type"] != s.asset_type:
                continue
            if s.criticality and a["criticality"] != s.criticality:
                continue
            if s.product and s.product.lower() not in a["product"].lower():
                continue
            if s.kev_only and not a["kev_cve_count"]:
                continue
            if s.overdue_only and not a["overdue"]:
                continue
            if s.severity:
                lo = SEVERITY_MIN.get(s.severity.upper())
                if lo is None or a["max_cvss"] is None or a["max_cvss"] < lo:
                    continue
            if s.min_cvss is not None:
                if a["max_cvss"] is None or a["max_cvss"] < s.min_cvss:
                    continue
            if s.stale_days is not None:
                d = _as_date(a.get("last_scan_date"))
                if d is None or (self.as_of - d).days < s.stale_days:
                    continue
            out.append(a)
        return out

    # -- filtering --------------------------------------------------------
    def _filter(self, s: QuerySpec) -> List[dict]:
        out = []
        for f in self.findings:
            if s.department and f["department"] != s.department:
                continue
            if s.asset_type and f["asset_type"] != s.asset_type:
                continue
            if s.criticality and f["criticality"] != s.criticality:
                continue
            if s.product and s.product.lower() not in f["product"].lower():
                continue
            if s.kev_only and not f["in_kev"]:
                continue
            if not s.include_uncertain and f["confidence"] == "UNCERTAIN":
                continue
            if s.severity:
                lo = SEVERITY_MIN.get(s.severity.upper())
                sc = f["cvss_score"]
                if lo is None or sc is None or sc < lo:
                    continue
            if s.min_cvss is not None:
                if f["cvss_score"] is None or f["cvss_score"] < s.min_cvss:
                    continue
            if s.overdue_only:
                d = _as_date(f.get("kev_due_date"))
                if d is None or d >= self.as_of:
                    continue
            if s.stale_days is not None:
                d = _as_date(f.get("last_scan_date"))
                if d is None or (self.as_of - d).days < s.stale_days:
                    continue
            out.append(f)
        return out

    @staticmethod
    def _sort(rows: List[dict], how: str) -> List[dict]:
        if how == "cvss":
            return sorted(rows, key=lambda f: (-(f["cvss_score"] or -1), f["asset_id"]))
        if how == "due_date":
            return sorted(rows, key=lambda f: (f.get("kev_due_date") or "9999",
                                               -f["ranked_score"]))
        return sorted(rows, key=lambda f: (-f["ranked_score"], f["asset_id"]))

    # -- main entry -------------------------------------------------------
    def run(self, s: QuerySpec) -> Dict[str, Any]:
        rows = self._sort(self._filter(s), s.sort_by)
        res: Dict[str, Any] = {
            "spec": s.to_dict(),
            "as_of": self.as_of.isoformat(),
            "matched_findings": len(rows),
            "rows": [],       # finding-level evidence
            "actions": [],    # remediation-action level (the unit of work)
            "facts": {},
            "caveats": self._caveats(rows),
        }

        handler = {
            PATCH_PRIORITY: self._patch_priority,
            GROUP_EXPOSURE: self._group,
            TOP_ASSET: self._top_asset,
            POSTURE_SUMMARY: self._posture,
            WHAT_IF_PATCH: self._what_if,
            STALE_SCANS: self._stale,
            COVERAGE: self._coverage,
            COUNT: self._count,
            OVERDUE_KEV: self._cve_level,
            CVE_LIST: self._cve_level,
            TOP_RISKS: self._plain,
        }.get(s.intent, self._plain)

        handler(s, rows, res)
        return res

    # -- handlers ---------------------------------------------------------
    # Handlers that answer "what should we do" operate on ACTIONS.
    # Handlers that answer "which CVEs" operate on FINDINGS.
    def _plain(self, s, rows, res):
        acts = self._filter_actions(s)[: s.limit]
        res["actions"] = acts
        res["rows"] = rows[: min(s.limit, 10)]
        res["facts"] = {
            "remediation_actions": len(self._filter_actions(s)),
            "underlying_findings": len(rows),
            "distinct_assets": len({a["asset_id"] for a in self._filter_actions(s)}),
            "distinct_cves": len({f["cve_id"] for f in rows}),
            "kev_cves": len({f["cve_id"] for f in rows if f["in_kev"]}),
            "shown": len(acts),
        }

    def _cve_level(self, s, rows, res):
        """For questions genuinely about CVEs ('list all CVEs sorted by CVSS',
        'what is past its CISA due date'). Here the CVE really is the unit, so
        we stay at finding level and do not roll up."""
        res["rows"] = rows[: s.limit]
        res["facts"] = {
            "total_matching": len(rows),
            "distinct_assets": len({f["asset_id"] for f in rows}),
            "distinct_cves": len({f["cve_id"] for f in rows}),
            "kev_count": sum(1 for f in rows if f["in_kev"]),
            "shown": min(s.limit, len(rows)),
        }

    def _count(self, s, rows, res):
        self._plain(s, rows, res)
        res["facts"]["asset_ids"] = sorted({a["asset_id"]
                                            for a in self._filter_actions(s)})

    def _top_asset(self, s, rows, res):
        acts = self._filter_actions(s)
        by_asset: Dict[str, List[dict]] = {}
        for a in acts:
            by_asset.setdefault(a["asset_id"], []).append(a)
        ranked = sorted(by_asset.items(),
                        key=lambda kv: -max(a["risk_score"] for a in kv[1]))
        res["facts"]["ranked_assets"] = [
            {
                "asset_id": aid,
                "hostname": aa[0]["hostname"],
                "department": aa[0]["department"],
                "criticality": aa[0]["criticality"],
                "asset_type": aa[0]["asset_type"],
                "top_score": max(a["risk_score"] for a in aa),
                "actions": len(aa),
                "kev_cves": sum(a["kev_cve_count"] for a in aa),
                "cve_count": sum(a["cve_count"] for a in aa),
            }
            for aid, aa in ranked[:5]
        ]
        if ranked:
            res["actions"] = sorted(ranked[0][1],
                                    key=lambda a: -a["risk_score"])
            res["rows"] = res["actions"][0]["top_findings"][:4]

    def _patch_priority(self, s, rows, res):
        acts = self._filter_actions(s)
        by_prod: Dict[str, List[dict]] = {}
        for a in acts:
            by_prod.setdefault(a["product"], []).append(a)
        # Rank a package by the worst single action it causes, then by how many
        # hosts it affects. Summing scores would just re-reward volume.
        ranked = sorted(
            by_prod.items(),
            key=lambda kv: (-max(a["risk_score"] for a in kv[1]), -len(kv[1])))
        res["facts"]["packages"] = [
            {
                "product": p,
                "worst_action_score": max(a["risk_score"] for a in aa),
                "assets_affected": len(aa),
                "asset_ids": sorted({a["asset_id"] for a in aa}),
                "cve_count": sum(a["cve_count"] for a in aa),
                "kev_cves": sorted({c for a in aa for c in a["kev_cves"]}),
                "max_cvss": max([a["max_cvss"] or 0 for a in aa]),
                "versions": sorted({a["installed_version"] for a in aa}),
                "critical_assets": len({a["asset_id"] for a in aa
                                        if a["criticality"] == "critical"}),
                "overdue": any(a["overdue"] for a in aa),
            }
            for p, aa in ranked[: s.limit]
        ]
        if ranked:
            res["actions"] = sorted(ranked[0][1], key=lambda a: -a["risk_score"])

    def _group(self, s, rows, res):
        key = s.group_by or "department"
        acts = self._filter_actions(s)
        buckets: Dict[str, List[dict]] = {}
        for a in acts:
            buckets.setdefault(a[key], []).append(a)
        # Rank units by their worst action, not by summed volume — otherwise
        # the unit with the most laptops always "wins".
        ranked = sorted(buckets.items(),
                        key=lambda kv: (-max(a["risk_score"] for a in kv[1]),
                                        -sum(a["kev_cve_count"] for a in kv[1])))
        res["facts"]["groups"] = [
            {
                key: g,
                "worst_action_score": max(a["risk_score"] for a in aa),
                "actions": len(aa),
                "kev_actions": sum(1 for a in aa if a["kev_cve_count"]),
                "kev_cves": len({c for a in aa for c in a["kev_cves"]}),
                "assets_affected": len({a["asset_id"] for a in aa}),
                "critical_assets_affected": len(
                    {a["asset_id"] for a in aa if a["criticality"] == "critical"}),
                "overdue_actions": sum(1 for a in aa if a["overdue"]),
                "top_action": max(aa, key=lambda a: a["risk_score"])["product"],
            }
            for g, aa in ranked
        ]
        totals: Dict[str, int] = {}
        for a in self.assets:
            totals[a[key]] = totals.get(a[key], 0) + 1
        res["facts"]["group_asset_totals"] = totals
        res["actions"] = acts[:5]

    def _posture(self, s, rows, res):
        all_f = self.findings
        acts = self.actions
        kev_acts = [a for a in acts if a["kev_cve_count"]]
        overdue_acts = [a for a in acts if a["overdue"]]
        res["facts"] = {
            "total_assets": len(self.assets),
            "assets_with_findings": len({a["asset_id"] for a in acts}),
            "remediation_actions": len(acts),
            "underlying_findings": len(all_f),
            "distinct_cves": len({f["cve_id"] for f in all_f}),
            "kev_actions": len(kev_acts),
            "kev_distinct_cves": len({f["cve_id"] for f in all_f if f["in_kev"]}),
            "kev_assets": len({a["asset_id"] for a in kev_acts}),
            "overdue_actions": len(overdue_acts),
            "overdue_assets": sorted({a["asset_id"] for a in overdue_acts}),
            "critical_assets_with_kev": len({a["asset_id"] for a in kev_acts
                                             if a["criticality"] == "critical"}),
            "worst_actions": [
                {"asset_id": a["asset_id"], "product": a["product"],
                 "score": a["risk_score"]} for a in acts[:3]],
            "confirmed": sum(1 for f in all_f if f["confidence"] == "CONFIRMED"),
            "likely": sum(1 for f in all_f if f["confidence"] == "LIKELY"),
            "uncertain": sum(1 for f in all_f if f["confidence"] == "UNCERTAIN"),
            "unassessed_software_instances": len(self.gaps),
        }
        res["actions"] = acts[:5]

    def _what_if(self, s, rows, res):
        if not s.product:
            res["facts"]["error"] = (
                "No product identified in the question. Specify a package, "
                "e.g. 'what would patching Apache HTTP Server achieve?'")
            return
        p = s.product.lower()
        affected_acts = [a for a in self.actions if p in a["product"].lower()]
        affected_f = [f for f in self.findings if p in f["product"].lower()]
        cves_before = {f["cve_id"] for f in self.findings}
        cves_after = {f["cve_id"] for f in self.findings if p not in f["product"].lower()}
        res["facts"] = {
            "product": s.product,
            "actions_closed": len(affected_acts),
            "assets_affected": sorted({a["asset_id"] for a in affected_acts}),
            "distinct_cves_removed": len({f["cve_id"] for f in affected_f}),
            "kev_cves_removed": sorted({f["cve_id"] for f in affected_f if f["in_kev"]}),
            "versions_present": sorted({a["installed_version"] for a in affected_acts}),
            "fleet_actions_before": len(self.actions),
            "fleet_actions_after": len(self.actions) - len(affected_acts),
            "fleet_distinct_cves_before": len(cves_before),
            "fleet_distinct_cves_after": len(cves_after),
            "net_cve_reduction": len(cves_before) - len(cves_after),
        }
        res["actions"] = sorted(affected_acts, key=lambda a: -a["risk_score"])

    def _stale(self, s, rows, res):
        days = s.stale_days or 30
        acts = self._filter_actions(s)
        by_asset: Dict[str, List[dict]] = {}
        for a in acts:
            by_asset.setdefault(a["asset_id"], []).append(a)
        res["facts"] = {
            "threshold_days": days,
            "as_of": self.as_of.isoformat(),
            "assets": [
                {
                    "asset_id": aid,
                    "hostname": aa[0]["hostname"],
                    "last_scan_date": aa[0]["last_scan_date"],
                    "days_since_scan": (self.as_of - _as_date(aa[0]["last_scan_date"])).days
                    if _as_date(aa[0]["last_scan_date"]) else None,
                    "criticality": aa[0]["criticality"],
                    "department": aa[0]["department"],
                    "actions": len(aa),
                    "kev_cves": sum(a["kev_cve_count"] for a in aa),
                    "max_cvss": max([a["max_cvss"] or 0 for a in aa]),
                }
                for aid, aa in sorted(by_asset.items(),
                                      key=lambda kv: -max(a["risk_score"] for a in kv[1]))
            ],
        }
        # Assets whose scan is stale but which have no findings at all are a
        # different and arguably worse problem: we know nothing about them.
        seen = {f["asset_id"] for f in self.findings}
        silent = []
        for a in self.assets:
            d = _as_date(a.get("last_scan_date"))
            if d and (self.as_of - d).days >= days and a["asset_id"] not in seen:
                silent.append({"asset_id": a["asset_id"],
                               "hostname": a["hostname"],
                               "last_scan_date": a["last_scan_date"],
                               "days_since_scan": (self.as_of - d).days,
                               "criticality": a["criticality"]})
        res["facts"]["stale_with_no_findings"] = silent
        res["rows"] = rows[: s.limit]

    def _coverage(self, s, rows, res):
        cov = self.index.get("coverage", {})
        by_kind: Dict[str, int] = {}
        for g in self.gaps:
            by_kind[g["kind"]] = by_kind.get(g["kind"], 0) + 1
        res["facts"] = {
            "products_total": cov.get("products_total"),
            "products_mapped": len(cov.get("products_mapped", [])),
            "products_unmapped": cov.get("products_unmapped", {}),
            "gap_instances_by_kind": by_kind,
            "os_matching": cov.get("os_matching"),
            "integrity_notes": self.index.get("integrity_notes", []),
            "examples": self.gaps[:12],
        }

    # -- caveats ----------------------------------------------------------
    def _caveats(self, rows: List[dict]) -> List[str]:
        out = []
        unc = [f for f in rows if f["confidence"] != "CONFIRMED"]
        if unc:
            n_l = sum(1 for f in unc if f["confidence"] == "LIKELY")
            n_u = sum(1 for f in unc if f["confidence"] == "UNCERTAIN")
            out.append(
                f"{len(unc)} of {len(rows)} matching findings are not fully "
                f"confirmed ({n_l} LIKELY, {n_u} UNCERTAIN). They are included "
                f"and labelled, not dropped.")
        noscore = sum(1 for f in rows if f["cvss_score"] is None)
        if noscore:
            out.append(f"{noscore} finding(s) have no published CVSS score and were "
                       f"scored at an assumed mid-range value.")
        if self.gaps:
            out.append(
                f"{len(self.gaps)} software instances across the fleet were not "
                f"assessed at all (unmapped products, or OS out of scope). Ask "
                f"'what did you not assess?' for the list.")
        return out
